### ISSUE TITLE
表达式里支持那些函数？我在 IR 里看好像只有 Max 和 Min

### ISSUE THREAD

**Issue by QingQiz** [QingQiz/NMSqL#19]
咱们表达式里应该支持那些函数，我试了试，只发现了 max 和 min，ir里到 strlen 我没找到对应到函数

**Comment by zhaoyiping0622** [comment]
+ count
+ min
+ max
+ sum
+ avg
+ fcnt 
+ length
+ substr

**Comment by zhaoyiping0622** [comment]
可以看sqlite的expr.c文件

**Comment by QingQiz** [comment]
callback 的函数有那些，我看 sqlite 会生成 p1 不同的 callback

**Comment by zhaoyiping0622** [comment]
你指的是IR callback吗 那个p1指的是传入回调函数的元素个数

**Comment by QingQiz** [comment]
ok 懂了
