### ISSUE TITLE
Between and 是否包含边界

### ISSUE THREAD

**Issue by zhaoyiping0622** [QingQiz/NMSqL#20]
https://github.com/QingQiz/NMSqL/blob/6e37cd40a178ed1e500b431f9935c4fb87e3914e/src/frontend/compiler/src/CodeGenerator/Expr.hs#L43
这里你现在的实现是不包含边界的？
我搜到是要包含边界的

**Comment by QingQiz** [comment]
`a between b and c` 应该对应 `a ∈ [b,c]` 吗

**Comment by QingQiz** [comment]
我现在确实是不包含边界的

**Comment by zhaoyiping0622** [comment]
ok

**Comment by QingQiz** [comment]
问题是需要改成包含边界的不

**Comment by zhaoyiping0622** [comment]
改吧
