### ISSUE TITLE
前端代码问题

### ISSUE THREAD

**Issue by zhaoyiping0622** [QingQiz/NMSqL#21]
https://github.com/QingQiz/NMSqL/blob/6e37cd40a178ed1e500b431f9935c4fb87e3914e/src/frontend/compiler/src/CodeGenerator/Expr.hs#L101
这里max和min的参数是两个吗？
```sql
Select max(a) from tablea;
```

对于这种sql你怎么处理

**Comment by zhaoyiping0622** [comment]
因为之前那个pr里的代码不是最新的了 所以那一批代码的cr我直接开issue了

**Comment by QingQiz** [comment]
不是，select-result 和 where 语句里能调用到函数不是同一批，我现在时打算动态注入函数定义

你看到的这些函数是只能在 where 里调用的

**Comment by QingQiz** [comment]
where 表达式里到 max 和 min 参数是两个

你说的那种还没实现

**Comment by zhaoyiping0622** [comment]
ok
