### ISSUE TITLE
Vm 及 cursor查找的问题

### ISSUE THREAD

**Issue by zhaoyiping0622** [QingQiz/NMSqL#23]
当查找失败时，sqlite关于cursor指向下一个还是前一个语焉不详，我想统一一下，所有涉及查找的操作都是lower_bound，及存在时指向存在的位置，否则指向第一个大于它的位置

**Comment by zhaoyiping0622** [comment]
另外，关于dbengine那边，如果当前cursor已经指向结尾，貌似没有相关的API来反馈。
我想要么加一个类似于isend的api表示结束，要么getkey操作返回null，讨论一下哪个更合适吧

**Comment by zhaoyiping0622** [comment]
@QingQiz @osmium18452

**Comment by QingQiz** [comment]
next 函数的返回值来指示是否结束不行吗

**Comment by QingQiz** [comment]
另外，查找失败的时候，cursor 无论指向哪似乎都无所谓？查找失败以后这个cursor 还会再次被用到吗？

**Comment by zhaoyiping0622** [comment]
那当查找一个元素时，我如何知道是否查找到了
现阶段查找操作的返回值貌似是此操作成功与否

**Comment by zhaoyiping0622** [comment]
另外，比方说我要查数据库中大于等于10的元素，但是数据库中并不存在等于10的元素，这时候如何查找

**Comment by QingQiz** [comment]
> 那当查找一个元素时，我如何知道是否查找到了
> 现阶段查找操作的返回值貌似是此操作成功与否

那查找的接口怎么改？成功返回字符串，失败返回NULL？

**Comment by QingQiz** [comment]
> 另外，比方说我要查数据库中大于等于10的元素，但是数据库中并不存在等于10的元素，这时候如何查找

sqlite 的索引只适用于相等的查询，大于等于的查询实际上需要遍历表，因此不存在lowerbound还是upperbound的问题

**Comment by zhaoyiping0622** [comment]
> > 那当查找一个元素时，我如何知道是否查找到了
> > 现阶段查找操作的返回值貌似是此操作成功与否
> 
> 那查找的接口怎么改？成功返回字符串，失败返回NULL？

我的想法是 当查找时 我先判断一下是否end 如果非end 则使用getkey判断是否相同

**Comment by zhaoyiping0622** [comment]
> > 另外，比方说我要查数据库中大于等于10的元素，但是数据库中并不存在等于10的元素，这时候如何查找
> 
> sqlite 的索引只适用于相等的查询，大于等于的查询实际上需要遍历表，因此不存在lowerbound还是upperbound的问题

感觉大于等于这种也应该上索引啊

**Comment by QingQiz** [comment]
> > sqlite 的索引只适用于相等的查询，大于等于的查询实际上需要遍历表，因此不存在lowerbound还是upperbound的问题
> 
> 感觉大于等于这种也应该上索引啊

大于等于上索引的话，那 nextIdx 表示什么，要不先不做

**Comment by QingQiz** [comment]
> > sqlite 的索引只适用于相等的查询，大于等于的查询实际上需要遍历表，因此不存在lowerbound还是upperbound的问题
> 
> 感觉大于等于这种也应该上索引啊

只有等于上索引的话，find 接口也可以废弃掉了，只需要实现 nextIndex 就行

**Comment by zhaoyiping0622** [comment]
那还有个问题 erase什么的删除之后cursor是指向前一个还是后一个呢

**Comment by zhaoyiping0622** [comment]
> > > sqlite 的索引只适用于相等的查询，大于等于的查询实际上需要遍历表，因此不存在lowerbound还是upperbound的问题
> > 
> > 
> > 感觉大于等于这种也应该上索引啊
> 
> 只有等于上索引的话，find 接口也可以废弃掉了，只需要实现 nextIndex 就行

dbengine提供的查找接口只有一个find啊

**Comment by QingQiz** [comment]
> 那还有个问题 erase什么的删除之后cursor是指向前一个还是后一个呢

前一个吧，，因为delete以后还要next，next 以后应该才是下一个

**Comment by QingQiz** [comment]
> > > > sqlite 的索引只适用于相等的查询，大于等于的查询实际上需要遍历表，因此不存在lowerbound还是upperbound的问题
> > > 
> > > 
> > > 感觉大于等于这种也应该上索引啊
> > 
> > 
> > 只有等于上索引的话，find 接口也可以废弃掉了，只需要实现 nextIndex 就行
> 
> dbengine提供的查找接口只有一个find啊

但是 find 似乎没什么用了，要不改接口？

**Comment by zhaoyiping0622** [comment]
> > > > > sqlite 的索引只适用于相等的查询，大于等于的查询实际上需要遍历表，因此不存在lowerbound还是upperbound的问题
> > > > 
> > > > 
> > > > 感觉大于等于这种也应该上索引啊
> > > 
> > > 
> > > 只有等于上索引的话，find 接口也可以废弃掉了，只需要实现 nextIndex 就行
> > 
> > 
> > dbengine提供的查找接口只有一个find啊
> 
> 但是 find 似乎没什么用了，要不改接口？

那改成什么样的？

**Comment by zhaoyiping0622** [comment]
> > 那还有个问题 erase什么的删除之后cursor是指向前一个还是后一个呢
> 
> 前一个吧，，因为delete以后还要next，next 以后应该才是下一个

如果删除的是第一个呢

**Comment by QingQiz** [comment]
> > > 那还有个问题 erase什么的删除之后cursor是指向前一个还是后一个呢
> > 
> > 
> > 前一个吧，，因为delete以后还要next，next 以后应该才是下一个
> 
> 如果删除的是第一个呢

 删除以后 cursor 应该不需要变吧，只是B树上多了个标记吧 ？

**Comment by QingQiz** [comment]
> > > > > > sqlite 的索引只适用于相等的查询，大于等于的查询实际上需要遍历表，因此不存在lowerbound还是upperbound的问题
> > > > > 
> > > > > 
> > > > > 感觉大于等于这种也应该上索引啊
> > > > 
> > > > 
> > > > 只有等于上索引的话，find 接口也可以废弃掉了，只需要实现 nextIndex 就行
> > > 
> > > 
> > > dbengine提供的查找接口只有一个find啊
> > 
> > 
> > 但是 find 似乎没什么用了，要不改接口？
> 
> 那改成什么样的？

应该只实现一个类似 IR 里的 nextIdx 的函数，find的话，ir里也没有对应的函数

**Comment by zhaoyiping0622** [comment]
> > > > 那还有个问题 erase什么的删除之后cursor是指向前一个还是后一个呢
> > > 
> > > 
> > > 前一个吧，，因为delete以后还要next，next 以后应该才是下一个
> > 
> > 
> > 如果删除的是第一个呢
> 
> 删除以后 cursor 应该不需要变吧，只是B树上多了个标记吧 ？

我觉得b树要修改 标记是打在底层数据上的吧

**Comment by QingQiz** [comment]
反正cursor 不需要变

**Comment by zhaoyiping0622** [comment]
> > > > 那还有个问题 erase什么的删除之后cursor是指向前一个还是后一个呢
> > > 
> > > 
> > > 前一个吧，，因为delete以后还要next，next 以后应该才是下一个
> > 
> > 
> > 如果删除的是第一个呢
> 
> 删除以后 cursor 应该不需要变吧，只是B树上多了个标记吧 ？

我觉得b树要修改 标记是打在底层数据上的吧

> > > > > > > sqlite 的索引只适用于相等的查询，大于等于的查询实际上需要遍历表，因此不存在lowerbound还是upperbound的问题
> > > > > > 
> > > > > > 
> > > > > > 感觉大于等于这种也应该上索引啊
> > > > > 
> > > > > 
> > > > > 只有等于上索引的话，find 接口也可以废弃掉了，只需要实现 nextIndex 就行
> > > > 
> > > > 
> > > > dbengine提供的查找接口只有一个find啊
> > > 
> > > 
> > > 但是 find 似乎没什么用了，要不改接口？
> > 
> > 
> > 那改成什么样的？
> 
> 应该只实现一个类似 IR 里的 nextIdx 的函数，find的话，ir里也没有对应的函数

我觉得这些用一个find 然后vm实现各种指令啊

**Comment by zhaoyiping0622** [comment]
cursor不变的话 后期时间复杂度直线上升啊 索引没啥用了

**Comment by QingQiz** [comment]
不是啊，删除的过程中 cursor不变，删除完了cursor就析构了。新构造的cursor对应的数据里已经没有删除了的数据了

**Comment by zhaoyiping0622** [comment]
删除完了cursor可以复用啊 cursor里存的应该是指向b树的一个指针，所以删除什么的操作都应该变成对b树的一个操作

**Comment by QingQiz** [comment]
> 我觉得这些用一个find 然后vm实现各种指令啊

啥指令要用find实现？

**Comment by zhaoyiping0622** [comment]
Move to 
Distinct
Found
Not found
Beginidx
暂时就看到这么多

**Comment by QingQiz** [comment]
草，删除结点后指向的位置你和 @EzioZz  商量商量？这块得看他怎么实现了

**Comment by QingQiz** [comment]
要我写的话肯定得有个超级结点，指向第一个结点

**Comment by EzioZz** [comment]
> 草，删除结点后指向的位置你和 @EzioZz 商量商量？这块得看他怎么实现了
> 要我写的话肯定得有个超级结点，指向第一个结点


可以传一个int参数进去，如果是0就回到一个指定的位置，1就next，（2就prev）
delete(Cursor*, int);

**Comment by EzioZz** [comment]
> > 草，删除结点后指向的位置你和 @EzioZz 商量商量？这块得看他怎么实现了
> > 要我写的话肯定得有个超级结点，指向第一个结点
> 
> 可以传一个int参数进去，如果是0就回到一个指定的位置，1就next，（2就prev）
> delete(Cursor*, int);

赵一平觉得用参数来控制比较麻烦，而且懒得改api，他说都指向后面的。

**Comment by zhaoyiping0622** [comment]
Cursor 删除操作之后 指向下一个位置
find操作都是lower_bound
当指向end时 get_key 和 get_value 都返回NULL
