### ISSUE TITLE
接口间字符串传递问题

### ISSUE THREAD

**Issue by zhaoyiping0622** [QingQiz/NMSqL#25]
上次说到：vm调用dbendine接口时传入的字符串是如下形式的：
```text
Offset1
Offset2
...
OffsetN
String1
String2
...
StringN
```
然后就有了几个问题：
+ 这里的偏移需要改成长度，如果不改，如何知道最后一个字符串何时结束（第一个offset一直是0，感觉有点浪费）
+ 每个字符串是否要保留零字符
+ dbengine返回的字符串是否要遵循以上格式
+ vm得到dbengine返回的字符串是否要将offset头部去掉再将字符串压栈（具体指的是FullKey这个IR如何处理，其他IR还没看）

暂时就想得到这几个问题

**Comment by zhaoyiping0622** [comment]
对了 还有一个问题
因为vm不知道具体这个字符串里有多少个字符串，也就是说不知道头部大小，所以如果vm要处理这种类型的字符串，可能在格式上需要增加点东西

**Comment by QingQiz** [comment]
- 格式改成这样吧： len1 str1 len2 str2 len3 str3 ...
- 改成上面的格式，零字符就无所谓了
- dbengine 返回给 VM 的字符串应该也需要遵守这个格式
- FullKey 我现在还不知道哪会用到，应该得带格式压吧，不然你出栈怎么 parse

**Comment by zhaoyiping0622** [comment]
如果带格式压栈的话，那么栈中就会有两种类型的字符串，带头部的和不带头部的，这样的话，你前端处理要特别小心

> * 格式改成这样吧： len1 str1 len2 str2 len3 str3 ...
> * 改成上面的格式，零字符就无所谓了
> * dbengine 返回给 VM 的字符串应该也需要遵守这个格式
> * FullKey 我现在还不知道哪会用到，应该得带格式压吧，不然你出栈怎么 parse

**Comment by zhaoyiping0622** [comment]
或者干脆所有VM的字符串都加一个头部？

**Comment by QingQiz** [comment]
我前端不需要处理字符串吧，，加头部的话会不会最后头部比数据都大。。

**Comment by zhaoyiping0622** [comment]
> 我前端不需要处理字符串吧，，加头部的话会不会最后头部比数据都大。。

```sql
Select * from a where a.x in ["a","b","c"] and a.x=A.y;
```
类似于这条sql
前端要将三个字符串压栈，这些是不带头部的，也要进行a.x和a.y的比较，这两个又是从dbengine那边获取的带着头部的字符串，这个怎么处理

**Comment by QingQiz** [comment]
这个我不管，因为字符串这种比较是VM做的

**Comment by zhaoyiping0622** [comment]
头部就占4个字节，感觉可以接受


> 这个我不管，因为字符串这种比较是VM做的

那我VM的字符串就带头部了

**Comment by QingQiz** [comment]
行

**Comment by zhaoyiping0622** [comment]
感觉还是要总结一下：
vm和dbengine相互传递字符串的规则如下：
```text
Len1
String1
Len2
String2
...
LenN
StringN
```
其中，String不带0字符
Len占四个字节，从len[4]（长度为4的char数组）到len（int）的转换方式为：
len=(Len[0]<<24)|(Len[1]<<16)|(Len[2]<<8)|Len[3]

@osmium18452 看到了就把这个issue关了

**Comment by zhaoyiping0622** [comment]
这里左移之前要先把char强制类型转换成int

**Comment by zhaoyiping0622** [comment]
我觉得dbengine返回给我的数据还要再加一个len表示返回给我的数据有多少个 [len,string]对
也就是说 dbengine返回给我的应该是 
len(len,string)+
如果不加的话，也可以考虑在cursor中加几个成员变量表示当前cursor指向的数据key有多少列，value有多少列

**Comment by QingQiz** [comment]
为啥需要，读到字符串结尾不就没了？？

**Comment by zhaoyiping0622** [comment]
返回value我又不知道这一行有几列
key的话也存在一个key有多列的情况
按理来说我是不知道cursor对应的是哪张表的

**Comment by QingQiz** [comment]
读完一个str，看当前位置是不是字符串结尾不是就可以了

**Comment by zhaoyiping0622** [comment]
返回给我的是一个char*

**Comment by zhaoyiping0622** [comment]
现在char*没有结尾标识符

**Comment by QingQiz** [comment]
c 类型字符串结尾必是 `\0`

**Comment by zhaoyiping0622** [comment]
这又不是语法强行规定的（逃

**Comment by zhaoyiping0622** [comment]
那就传递过程中都以0字符结尾咯？

**Comment by zhaoyiping0622** [comment]
不对 这样还有问题 因为我长度里会含有零字符 所以零字符不能作为结尾标识符

**Comment by QingQiz** [comment]
那就开头四个字节表示长度吧
