### ISSUE TITLE
record number相关问题

### ISSUE THREAD

**Issue by zhaoyiping0622** [QingQiz/NMSqL#29]
我发现sqlite好多操作都是直接将record number压栈，我们还要不要保留record number这东西。
如果保留的话，dbengine需要给我增加接口。
如果不保留的话，每次压栈一个记录有可能会有性能损耗，以及之后可能会碰到一些其他问题（我猜的）。

**Comment by zhaoyiping0622** [comment]
例如 idx相关 list相关IR 都是操作record number的
另外，IR中也有一些与record number相关的指令，例如NewRecno/recno，这些我暂时都还没实现，如果要实现的话，需要dbengine提供接口

**Comment by QingQiz** [comment]
record number 是个什么东西啊

**Comment by zhaoyiping0622** [comment]
大概就是 数据库里每一行都有一个编号 叫做record number

**Comment by QingQiz** [comment]
需要增加啥接口

**Comment by zhaoyiping0622** [comment]
获取一个recordnumber
通过recordnumber获取value
暂时只想得到这些

**Comment by zhaoyiping0622** [comment]
第一个指的是 获取一个新的record number

**Comment by zhaoyiping0622** [comment]
感觉recno好像没啥用

**Comment by QingQiz** [comment]
我也感觉没啥用，，

**Comment by QingQiz** [comment]
这玩意感觉没有好像也没啥问题

**Comment by zhaoyiping0622** [comment]
不过感觉删了这玩意
好像很多IR都要改了

**Comment by zhaoyiping0622** [comment]
那个makeidxkey就可以直接删了

**Comment by zhaoyiping0622** [comment]
不过这个recordnumber可以唯一标示一条数据 不知道这个有没有什么应用场景

**Comment by zhaoyiping0622** [comment]
那就先删了？
感觉IR好多要修改了

**Comment by QingQiz** [comment]
行，删了吧
