### ISSUE TITLE
b+树insert的时候，涉及到写数据，page的接口是什么。

### ISSUE THREAD

**Issue by EzioZz** [QingQiz/NMSqL#35]
b+树insert的时候，涉及到写数据，page的接口是什么。data应该怎么传。data的数据结构是什么。 @PtvMiKu @QingQiz。

**Comment by QingQiz** [comment]
data的格式应该用的是 https://github.com/QingQiz/NMSqL/issues/25 讨论的字符串格式

page的接口你问问py

**Comment by PtvMiKu** [comment]
page的接口准备是根据sqlite的来写
int nmsql_pager_write(void* pData)


sqlite这部分的源码是这样的
```c
/*
** Mark a data page as writeable.  The page is written into the journal 
** if it is not there already.  This routine must be called before making
** changes to a page.
**
** The first time this routine is called, the pager creates a new
** journal and acquires a write lock on the database.  If the write
** lock could not be acquired, this routine returns SQLITE_BUSY.  The
** calling routine must check for that routine and be careful not to
** change any page data until this routine returns SQLITE_OK.
*/
int sqlite_pager_write(void *pData){
  if( pPager->state==SQLITE_READLOCK ){
    pPager->jfd = open(pPager->zJournal, O_RDWR|O_CREAT, 0644);
    if( pPager->jfd<0 ){
      return SQLITE_CANTOPEN;
    }
    if( sqlite_pager_lock(pPager->jfd, 1) ){
      close(pPager->jfd);
      pPager->jfd = -1;
      return SQLITE_BUSY;
    }
    sqlite_pager_unlock(pPager->fd);
    if( sqlite_pager_lock(pPager->fd, 1) ){
      close(pPager->jfd);
      pPager->jfd = -1;
      pPager->state = SQLITE_UNLOCK;
      sqlite_pager_reset(pPager);
      return SQLITE_PROTOCOL;
    }
    pPager->state = SQLITE_WRITELOCK;
    pPager->jSize = 0;
  }
  /* Write this page to the journal */
}
```

**Comment by QingQiz** [comment]
这个看起来不能直接用吧，和咱们商量的差别应该还挺大？ @zhaoyiping0622 你来讲讲？

**Comment by zhaoyiping0622** [comment]
我觉得吧，只要两个接口

```cpp
address_t getNewAddress(size_t size); // 向pager请求一个可以放size大小数据的空间
int write(address_t,char*,size_t size);
```

edit:
其实感觉就一个接口也行

```cpp
address_t putDataToNewAddress(char* data,size_t size);
```

**Comment by QingQiz** [comment]
咱们这个插数据的时候，得 @PtvMiKu 来找到一个可用的page，然后写page，返回page号和page内偏移。和sqlite差别应该挺大？

**Comment by zhaoyiping0622** [comment]
这个 sqlite_pager_write 没看懂 我再研究研究
@PtvMiKu 你这是哪个版本的代码？

**Comment by EzioZz** [comment]
> 咱们这个插数据的时候，得 @PtvMiKu 来找到一个可用的page，然后写page，返回page号和page内偏移。和sqlite差别应该挺大？

原来的逻辑不太符合B+树，数据的局部性原理。B+树里一个node是一个page。一般情况下，是查到已经创建好的page当中。当一个page都被插满的时候，才需要创建一个page。

**Comment by zhaoyiping0622** [comment]
> > 咱们这个插数据的时候，得 @PtvMiKu 来找到一个可用的page，然后写page，返回page号和page内偏移。和sqlite差别应该挺大？
> 
> 原来的逻辑不太符合B+树，数据的局部性原理。B+树里一个node是一个page。一般情况下，是查到已经创建好的page当中。当一个page都被插满的时候，才需要创建一个page。

这东西是pager统一管理吧，反正新增数据都是在一块空闲page上，这块空闲page不够了再搞一块新的

**Comment by EzioZz** [comment]
> > > 咱们这个插数据的时候，得 @PtvMiKu 来找到一个可用的page，然后写page，返回page号和page内偏移。和sqlite差别应该挺大？
> > 
> > 
> > 原来的逻辑不太符合B+树，数据的局部性原理。B+树里一个node是一个page。一般情况下，是查到已经创建好的page当中。当一个page都被插满的时候，才需要创建一个page。
> 
> 这东西是pager统一管理吧，反正新增数据都是在一块空闲page上，这块空闲page不够了再搞一块新的

page具体位置是pager管的，但是一个node是要对应一个page，整个page读写，方便IO。

**Comment by zhaoyiping0622** [comment]
一个node对应于一个结构体 肯定是在一个page上啊

**Comment by EzioZz** [comment]
> 一个node对应于一个结构体 肯定是在一个page上啊

对，那就是我之前说那个做法吧。没问题吧。
![image](https://user-images.githubusercontent.com/22981348/99556533-9bf5b280-29fc-11eb-949d-a9fe79401595.png)

**Comment by zhaoyiping0622** [comment]
> > 一个node对应于一个结构体 肯定是在一个page上啊
> 
> 对，那就是我之前说那个做法吧。没问题吧。
> ![image](https://user-images.githubusercontent.com/22981348/99556533-9bf5b280-29fc-11eb-949d-a9fe79401595.png)

对 但是我感觉 @QingQiz 也是这个意思啊

**Comment by EzioZz** [comment]
> page的接口准备是根据sqlite的来写
> int nmsql_pager_write(void* pData)
> 
他的代码没用pData，感觉像是在设置标记，而且他都没输入cursor。我传给你的数据我觉得应该是一个cursor，一个vois* pData。不知道够不够，现在还没确定。

**Comment by zhaoyiping0622** [comment]
> > page的接口准备是根据sqlite的来写
> > int nmsql_pager_write(void* pData)
> 
> 他的代码没用pData，感觉像是在设置标记，而且他都没输入cursor。我传给你的数据我觉得应该是一个cursor，一个vois* pData。不知道够不够，现在还没确定。

输入cursor？
pager 应该看不到上层的结构
我觉得应该传一个char*
还要传个size
可能还要加点什么东西 不然我担心到时候读不出来

**Comment by EzioZz** [comment]
> > > page的接口准备是根据sqlite的来写
> > > int nmsql_pager_write(void* pData)
> > 
> > 
> > 他的代码没用pData，感觉像是在设置标记，而且他都没输入cursor。我传给你的数据我觉得应该是一个cursor，一个vois* pData。不知道够不够，现在还没确定。
> 
> 输入cursor？
> pager 应该看不到上层的结构
> 我觉得应该传一个char*
> 还要传个size
> 可能还要加点什么东西 不然我担心到时候读不出来

cursor就是给指个地方，哪里写入数据。或者传一个address也行。
size可能需要。

**Comment by zhaoyiping0622** [comment]
> > > > page的接口准备是根据sqlite的来写
> > > > int nmsql_pager_write(void* pData)
> > > 
> > > 
> > > 他的代码没用pData，感觉像是在设置标记，而且他都没输入cursor。我传给你的数据我觉得应该是一个cursor，一个vois* pData。不知道够不够，现在还没确定。
> > 
> > 
> > 输入cursor？
> > pager 应该看不到上层的结构
> > 我觉得应该传一个char*
> > 还要传个size
> > 可能还要加点什么东西 不然我担心到时候读不出来
> 
> cursor就是给指个地方，哪里写入数据。或者传一个address也行。
> size可能需要。

我以为你是说写新页
修改老数据的话 传address_t指定写入位置 char*指定要写的数据 size指定要写的数据量

**Comment by zhaoyiping0622** [comment]
对了 page的接口有定吗？

**Comment by QingQiz** [comment]
似乎没有

**Comment by zhaoyiping0622** [comment]
那我近期开个issue讨论一下吧
