### ISSUE TITLE
dbengine 返回数据再利用问题

### ISSUE THREAD

**Issue by zhaoyiping0622** [QingQiz/NMSqL#38]
dbengine返回的数据全是字符串，但是当我们要对数据排序的时候，需要知道数据的类型，但是vm这一层只能知道vm返回的数据有几列，每一列数据的字符串形式是怎样的，不知道类型。

我想的解决方案有两种：

1. dbengine返回的数据用1个字节表示这个数据是什么类型的
2. 增加类型相关的IR，由前端来指定将此数据的某一列变换为某类型的数据，并压栈

**Comment by QingQiz** [comment]
我选择第一种方案

**Comment by QingQiz** [comment]
话说字符串长度用4个字节不会有点浪费吗

**Comment by zhaoyiping0622** [comment]
> 话说字符串长度用4个字节不会有点浪费吗

那就改成三个字节？加上标记位方便对齐

**Comment by QingQiz** [comment]
要不俩字节 （长度65535够用了）留一个字节备用

**Comment by zhaoyiping0622** [comment]
OK 那传入数据也这个格式吧 统一一下

**Comment by QingQiz** [comment]
ok，你要不开个新issue 总结一下？
