### ISSUE TITLE
关于dbengine使用聚簇索引和二级索引方式的建议

### ISSUE THREAD

**Issue by EzioZz** [QingQiz/NMSqL#47]
NMSQL中分为两种索引：聚簇索引（clustered index）和次要索引（secondary index）。这两种索引都是一种差不多的B+树。

 一张表有且只有一个聚簇索引，也就是只有一个主键（虽然主键是一个逻辑上的概念，这里先这么叫）。主键会决定了数据的真实存储位置。次要索引可以有很多，不会影响数据的实际存储位置。

dbengine使用B+Tree接口的时候需要注意以下几点：

1. 如果用户没有指定建立一个聚簇索引，那么dbengine需要创建一个虚拟的主键，用于聚簇。
2. 聚簇索引的lead node存的是真实的数据，而次要索引存的leaf node存的data是用于聚簇的主键（不直接存row pointer是为了减少节点合并和分裂时候的开销）。
3. 对一张表进行操作的时候，要对所以的索引进行同步的操作。

@osmium18452

**Comment by osmium18452** [comment]
等我吃完饭看看

**Comment by osmium18452** [comment]
Roger
