### ISSUE TITLE
接口对不上啊，见下文

### ISSUE THREAD

**Issue by osmium18452** [QingQiz/NMSqL#48]
接口对不上啊，见下文

-[ ] insert 时要插入 key-value 对，但是 Btree 的接口里没给 value
-[ ] erase 时要只要删除一个节点就可以了，不需要key

**Comment by osmium18452** [comment]
@EzioZz

**Comment by osmium18452** [comment]
咋整啊？不管了？

**Comment by EzioZz** [comment]
邮件没有收到，应该是没有assign我。insert那个我改一下。erase不要key，怎么确定删哪一个？

**Comment by osmium18452** [comment]
> 邮件没有收到，应该是没有assign我。insert那个我改一下。erase不要key，怎么确定删哪一个？

@zhaoyiping0622

**Comment by EzioZz** [comment]
#50 根据doc/../vm.md修改了接口。remove不再需要key。

**Comment by EzioZz** [comment]
#50 根据doc/../vm.md修改了接口。remove不再需要key。
