### ISSUE TITLE
关于callback调用

### ISSUE THREAD

**Issue by zhaoyiping0622** [QingQiz/NMSqL#56]
callback 操作是出栈p1个元素，放进一个数组中 调用callback函数，p1个元素就是结果的p1列

在这里规定一下，栈顶是第0列，然后是第1列，以此类推

在callback函数调用中，传入的元素内容也是以dbengine和vm数据调用格式存储，具体见#40

**Comment by QingQiz** [comment]
栈顶最后一列吧，我是按 0-N 列的顺序压栈的

**Comment by zhaoyiping0622** [comment]
行吧
