### ISSUE TITLE
cookie是啥

### ISSUE THREAD

**Issue by osmium18452** [QingQiz/NMSqL#57]

**Comment by zhaoyiping0622** [comment]
每个数据库文件里都有一个
当要修改任意的表结构的时候 要修改cookie
当一条sql执行完之后 要检验cookie 若和执行之前的cookie不同 就要回滚

**Comment by zhaoyiping0622** [comment]
https://github.com/QingQiz/NMSqL/blob/893e72da3bd232807a17a1a290024966a977f454/src/backend/include/DbEngineInterface.h#L70
@QingQiz 这里是不是有问题 cookie是一个数据库一个 应该放在数据库的metadata里 然后你前端生成IR的时候也要调用一下getcookie

**Comment by QingQiz** [comment]
直接让他把相同的cookie 放在每一个表的md里，我懒得改了

**Comment by zhaoyiping0622** [comment]
> 直接让他把相同的cookie 放在每一个表的md里，我懒得改了

这样的话 改的时候每个表的md都要改了

**Comment by zhaoyiping0622** [comment]
对了 cookie修改的时候要原子操作 @osmium18452

**Comment by QingQiz** [comment]
不是，我的意思是只有一个cookie，但是给我返回cookie的时候是复制成 N 份 放在返回给我的 table-md 里

**Comment by zhaoyiping0622** [comment]
> 直接让他把相同的cookie 放在每一个表的md里，我懒得改了

你的意思是传的时候把cookie放里面？然后数据库里还是存在数据库文件的md里？

**Comment by zhaoyiping0622** [comment]
OK

**Comment by QingQiz** [comment]
对

**Comment by osmium18452** [comment]
> 不是，我的意思是只有一个cookie，但是给我返回cookie的时候是复制成 N 份 放在返回给我的 table-md 里

啊？那修改的时候不照样还得改每个表的md？

**Comment by zhaoyiping0622** [comment]
外部调用的时候再修改 类似于copy on write 或者干脆不存这个字段了 当外部调用的时候再把这个字段填进去

**Comment by QingQiz** [comment]
> > 不是，我的意思是只有一个cookie，但是给我返回cookie的时候是复制成 N 份 放在返回给我的 table-md 里
> 
> 啊？那修改的时候不照样还得改每个表的md？

不是，你给我返回的 md 和数据库里存的 md 不是同一种格式，你给我的那个格式里每个表需要有一个 cookie， 那个 cookie 直接全置为数据库的 cookie

**Comment by QingQiz** [comment]
> 外部调用的时候再修改 类似于copy on write 或者干脆不存这个字段了 当外部调用的时候再把这个字段填进去

啥意思？get的时候顺便 set 一个新的？

**Comment by zhaoyiping0622** [comment]
> > 外部调用的时候再修改 类似于copy on write 或者干脆不存这个字段了 当外部调用的时候再把这个字段填进去
> 
> 啥意思？get的时候顺便 set 一个新的？

外部调用 gettablemetadata的时候 再修改tablemetadata里的cookie
