### ISSUE TITLE
dbengine给VM的接口中如何传递page号

### ISSUE THREAD

**Issue by zhaoyiping0622** [QingQiz/NMSqL#64]
rt @osmium18452

**Comment by zhaoyiping0622** [comment]
以及需要添加接口

**Comment by zhaoyiping0622** [comment]
createTable
createIndex
这两个要修改
destroy
clear
要添加

**Comment by osmium18452** [comment]
为啥还要page号？这不是b树管吗？

**Comment by zhaoyiping0622** [comment]
创建表 删表 清空表里内容 都需要page号

**Comment by osmium18452** [comment]
那就直接返回个int？

**Comment by zhaoyiping0622** [comment]
在后端 page号都是int吗？

**Comment by osmium18452** [comment]
是吧，我看b树的返回值都是int

**Comment by zhaoyiping0622** [comment]
@PtvMiKu @EzioZz 确认一下？后端page号都是int吗

**Comment by osmium18452** [comment]
![image](https://user-images.githubusercontent.com/41052057/102006080-35dd2080-3d59-11eb-90ee-2af812915488.png)

**Comment by zhaoyiping0622** [comment]
行吧
