### ISSUE TITLE
opPut 的问题

### ISSUE THREAD

**Issue by QingQiz** [QingQiz/NMSqL#68]
- sqlite 中 opPut 默认是将 NewRecno 和 MakeRecord 的结果进行出栈
- 我们将 NewRecno 删除了
- opPut 的默认 key 部分怎么搞

**Comment by zhaoyiping0622** [comment]
那要看后端对默认b树是如何处理的 我的想法是空字符串

**Comment by QingQiz** [comment]
直接重新启用 NewRecno 吧，key 需压是唯一的，空字符串恐怕不行

**Comment by zhaoyiping0622** [comment]
key不能是唯一的

**Comment by QingQiz** [comment]
反正就启用 NewRecno 吧

**Comment by zhaoyiping0622** [comment]
idx后缀的指令都是处理key不唯一的情况

**Comment by QingQiz** [comment]
都行了，大不了你 NewRecno 直接压栈一个空字符串

**Comment by zhaoyiping0622** [comment]
关键是 启用recon有什么用吗
启用了它 我觉得好多接口都要改了

**Comment by QingQiz** [comment]
没啥要改的吧，你可以重新定义它的意思为 默认索引的默认KEY

**Comment by zhaoyiping0622** [comment]
那什么情况下必须要使用recno？

**Comment by QingQiz** [comment]
所以你可以重命名 recno 为 defaultKey，因为这里万一要改的话，我这边得大改，所以我想要重新启用这个，提供一个 defaultKey 的功能

**Comment by zhaoyiping0622** [comment]
defaultKey作用是什么？压栈空字符串？

**Comment by QingQiz** [comment]
对，暂时这样就行

**Comment by zhaoyiping0622** [comment]
那你加吧
