### ISSUE TITLE
数据库元信息有哪些？

### ISSUE THREAD

**Issue by QingQiz** [QingQiz/NMSqL#82]
我能想到的需要

- PageSize（4k）
- 当前最大的 page 号
- 所有小于最大 page 的可用的 page 号 （优化 CreatePage）
- NMSqL_Master 表的 根 page 号
- 所有表的名字（这个存疑，应为前端需要加一个获取所有表名字的接口，不知道能否用其他实现方式）

**Comment by zhaoyiping0622** [comment]
PageSize程序里写死成4K 不用放进元信息里
最大page号需要
> 所有小于最大 page 的可用的 page 号 （优化 CreatePage）

这个只需要放一个，然后把所有可用page号组成一个链表就行了
> NMSqL_Master 表的 根 page 号

写死成1 不想移动这个东西
> 所有表的名字（这个存疑，应为前端需要加一个获取所有表名字的接口，不知道能否用其他实现方式）

dbengine初始化的时候扫一下NMSqL_Master表获取就行了
元信息最好放些固定长度的东西吧

**Comment by QingQiz** [comment]
所有可用的page号我打算是分一个page专门存这玩意

**Comment by QingQiz** [comment]
那就只剩
- 当前最大的 page 号
- 所有小于最大 page 的可用的 page 号 （优化 CreatePage）

没啥要补充的吗

**Comment by zhaoyiping0622** [comment]
cookie应该也要放

**Comment by zhaoyiping0622** [comment]
> 所有可用的page号我打算是分一个page专门存这玩意

感觉这样就浪费了一页存储啊 而且如果可用page超过1个page怎么办

**Comment by zhaoyiping0622** [comment]
我现在的想法是
page1->page2->page3...
然后元信息里只存page1

**Comment by QingQiz** [comment]
对，我的想法就是这个
