### ISSUE TITLE
master表各列的类型及含义

### ISSUE THREAD

**Issue by zhaoyiping0622** [QingQiz/NMSqL#83]
@QingQiz 你来总结一下？

**Comment by QingQiz** [comment]
https://github.com/QingQiz/NMSqL/blob/c8c679c5ee7a1a55dfe63c082452efa0538a040d/src/frontend/compiler/src/CodeGenerator/Generator/Table.hs#L57-L61

- type: `index` or `table`
- key: index name or table name
- table:  table name involved
- page: root page
- value: sql involved, for example: `create table xxx (a int)`

**Comment by zhaoyiping0622** [comment]
那后端该如何处理这个表
怎么从value里获取当前这个index是哪几列
如何获取这个表有哪些列
正则表达式？

**Comment by QingQiz** [comment]
应该是了，，我前端稍微处理了一下sql，所以格式很固定

**Comment by QingQiz** [comment]
https://github.com/QingQiz/NMSqL/blob/c8c679c5ee7a1a55dfe63c082452efa0538a040d/src/frontend/compiler/src/Test/CodeGenerator/TestCodeGenerator.hs#L675

**Comment by zhaoyiping0622** [comment]
ok
